### ISSUE TITLE
Refactor and restructure styles for reduced complexity

### ISSUE THREAD

**Issue by guylepage3** [papriika/papriika.com#21]
**Description**
Refactor and restructure styles for reduced complexity and to match new component based styling.

Currently we are using a mixture of SCSS, CSS, inline and Styled Components for styling universe.engineering. Since Meta v1.5's new stand alone structure, we are now able to apply a more focused SCSS styling methodology, making it much easier to manage styles and contribute to the project.

**Tasks**
- [x] Design new SCSS component file architecture.
- [x] Apply new SCSS structure.
- [x] Pull all CSS styles into SCSS component files.
- [x] Pull out all unnecessary inline styles.
- [x] Find all styles that can be consolidated and/or removed to reduce complexity and bloat.
- [x] Test.
- [x] Push live.

**Comment by guylepage3** [comment]
New SCSS design

```text
scss/
├── _alert.scss
├── _button-group.scss
├── _buttons.scss
├── _card.scss
├── _code.scss
├── _components.scss
├── _custom-forms.scss
├── _dropdown.scss
├── _forms.scss
├── _functions.scss
├── _grid.scss
├── _images.scss
├── _input-group.scss
├── _jumbotron.scss
├── _list-group.scss
├── _meta-cts.scss
├── _mixins.scss
├── _nav.scss
├── _navbar.scss
├── _popover.scss
├── _reboot.scss
├── _root.scss
├── _tables.scss
├── _tooltip.scss
├── _transitions.scss
├── _type.scss
├── _utilities.scss
├── _variables.scss
├── mixins/
|   └── _media-queries.scss
└── papriika.scss
```

**Comment by guylepage3** [comment]
Final testing complete. Done.
