### ISSUE TITLE
Papriika.com v2 app design & dev tasks

### ISSUE THREAD

**Issue by guylepage3** [papriika/papriika.com#24]
**Description**
Define papriika.com v2 app design & dev tasks

**Tasks**
- [ ] Home page hero update.
  - [ ] Add search field.
- [ ] Create destination page.
  - [ ] Heading.
  - [ ] Description.
  - [ ] Form.
    - [ ] Destination.
    - [ ] Booking dates.
    - [ ] Name.
    - [ ] Email address.
    - [ ] Phone number.
    - [ ] Submit button.
- [ ] Open source database? (We might be able to skip this for v2.0).

**Comment by guylepage3** [comment]
The following are @aseoconnor's user flow designs from issue [#23 Papriika.com v2 user flow & purchase process](https://github.com/papriika/papriika.com/issues/23).

<img width="643" alt="Screenshot 2019-03-26 09 46 31" src="https://user-images.githubusercontent.com/1711854/56219209-56a91c00-6034-11e9-9a14-718067a55dd8.png">
<img width="638" alt="Screenshot 2019-03-26 09 47 05" src="https://user-images.githubusercontent.com/1711854/56219211-56a91c00-6034-11e9-8023-bee1afbb808f.png">
