### ISSUE TITLE
Build Slack invite form & update on web app

### ISSUE THREAD

**Issue by guylepage3** [papriika/papriika.com#33]
**Description**
Build Slack invite form / express server for easy invite link change as Slack may cancel our link again. This will allow us to make one simple change instead of 20.

**Tasks**
- [ ] Research the best method for building out form
- [ ] Generate Slack token - https://api.slack.com/custom-integrations/legacy-tokens
- [ ] Add [reCAPTCHA](https://www.google.com/recaptcha/intro/v3.html)
- [ ] Deploy app to Heroku
- [ ] Update link on papriika.com

**NOTE**
SLACK_SUBDOMAIN is only the `papriika`. not `papriika.slack.com`.

**References**
- [npm Slackin](https://www.npmjs.com/package/slackin)
- [Slackin (GitHub)](https://github.com/rauchg/slackin)

**Comment by guylepage3** [comment]
We need to get Slackin setup for papriika.com

<img width="1438" alt="Screenshot 2020-06-24 18 40 51" src="https://user-images.githubusercontent.com/1711854/85635230-5d291f80-b64b-11ea-8903-8767ec47e81f.png">
