### ISSUE TITLE
Implement temporary Papriika.com "Upgrade" page

### ISSUE THREAD

**Issue by guylepage3** [papriika/papriika.com#5]
**Description**
Implement temporary Papriika.com "Upgrade" page

**Tasks**
- [x] Pull in old html
- [x] Pull in old css
- [x] Pull in old js
- [x] Update copy, styles, etc.
- [x] Update meta data

**Comment by guylepage3** [comment]
Done
